server:
  port: 8003

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.169.138:3306/springcloud2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: springcloud2020
    password: springcloud2020

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版
      #defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: payment8003
    prefer-ip-address: true   #访问路径是否显示ip地址

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.jijl.springcloud.entities
